### PR TITLE
Add Organization and Package response

### PR DESCRIPTION
**Pull request by er1c**
some additional endpoints

### CODE REVIEW

**Comment by er1c** [comment]
@eed3si9n ugh, sorry to bother you, it looks like CI needs a github token with `read:packages`

**Comment by eed3si9n** [comment]
ok. I can generate a new token and set it as a secret.

**Comment by eed3si9n** [comment]
Done - https://github.com/eed3si9n/repatch-github/pull/7

**Comment by eed3si9n** [comment]
I just invited you to be a committer on this repo. I wonder if that would improve the secrets situation on the PR.

**Comment by eed3si9n** [comment]
```scala
[error]     ! return a json object that can be parsed using `Organization`
[error]  java.util.concurrent.ExecutionException: java.lang.RuntimeException: Key repos_url was not found in JObject(List((name,JString(bronze)), (space,JInt(976562499)), (private_repos,JInt(10)), (filled_seats,JInt(217)), (seats,JInt(0)))) (NettyResponseFuture.java:201)
[error] org.asynchttpclient.netty.NettyResponseFuture.get(NettyResponseFuture.java:201)
```

**Comment by er1c** [comment]
Moved to: https://github.com/eed3si9n/repatch-github/pull/8

**Pull request closed without merging**
